import 'dotenv/config';
import { connectDB, ensureIndexes, getDb } from './db';

const destinations = [
    {
        name: 'Santorini, Greece',
        slug: 'santorini-greece',
        country: 'Greece',
        images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop'],
        shortDescription: 'Iconic blue-domed churches and breathtaking sunsets over the Aegean.',
        fullDescription: 'Santorini is a volcanic island in the Cyclades group of the Greek islands, known for its dramatic views and stunning sunsets.',
        priceRange: { min: 800, max: 2500 },
        category: 'beach',
        rating: 4.8,
        bestTimeToVisit: 'June to September',
        tags: ['beach', 'romantic', 'luxury', 'island'],
        createdAt: new Date(), updatedAt: new Date(),
    },
    {
        name: 'Kyoto, Japan',
        slug: 'kyoto-japan',
        country: 'Japan',
        images: ['https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=600&h=400&fit=crop'],
        shortDescription: 'Ancient temples, cherry blossoms, and traditional tea houses.',
        fullDescription: 'Kyoto, once the capital of Japan, is famous for its classical Buddhist temples, gardens, imperial palaces, and traditional wooden houses.',
        priceRange: { min: 500, max: 1800 },
        category: 'city',
        rating: 4.9,
        bestTimeToVisit: 'March to May, October to November',
        tags: ['culture', 'history', 'temples', 'city'],
        createdAt: new Date(), updatedAt: new Date(),
    },
    {
        name: 'Bali, Indonesia',
        slug: 'bali-indonesia',
        country: 'Indonesia',
        images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&h=400&fit=crop'],
        shortDescription: 'Tropical paradise with rice terraces, temples, and surf beaches.',
        fullDescription: 'Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches, and coral reefs.',
        priceRange: { min: 400, max: 1500 },
        category: 'beach',
        rating: 4.7,
        bestTimeToVisit: 'April to October',
        tags: ['beach', 'culture', 'temples', 'nature'],
        createdAt: new Date(), updatedAt: new Date(),
    },
    {
        name: 'Paris, France',
        slug: 'paris-france',
        country: 'France',
        images: ['https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=400&fit=crop'],
        shortDescription: 'The City of Light — romance, art, and world-class cuisine.',
        fullDescription: 'Paris is the capital of France, a major European city and a global center for art, fashion, gastronomy, and culture.',
        priceRange: { min: 1000, max: 3000 },
        category: 'city',
        rating: 4.8,
        bestTimeToVisit: 'April to June, September to October',
        tags: ['romantic', 'culture', 'food', 'art'],
        createdAt: new Date(), updatedAt: new Date(),
    },
    {
        name: 'Swiss Alps, Switzerland',
        slug: 'swiss-alps-switzerland',
        country: 'Switzerland',
        images: ['https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=600&h=400&fit=crop'],
        shortDescription: 'Majestic mountains, skiing, and breathtaking alpine views.',
        fullDescription: 'The Swiss Alps are the Swiss portion of the Alps mountain range, a popular destination for skiing and mountaineering.',
        priceRange: { min: 1500, max: 5000 },
        category: 'mountain',
        rating: 4.9,
        bestTimeToVisit: 'December to March (skiing), June to September (hiking)',
        tags: ['mountain', 'adventure', 'skiing', 'nature'],
        createdAt: new Date(), updatedAt: new Date(),
    },
    {
        name: 'Dubai, UAE',
        slug: 'dubai-uae',
        country: 'UAE',
        images: ['https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=400&fit=crop'],
        shortDescription: 'Futuristic city of luxury shopping and ultramodern architecture.',
        fullDescription: 'Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture, and lively nightlife.',
        priceRange: { min: 1500, max: 5000 },
        category: 'city',
        rating: 4.5,
        bestTimeToVisit: 'November to March',
        tags: ['luxury', 'shopping', 'architecture', 'city'],
        createdAt: new Date(), updatedAt: new Date(),
    },
    {
        name: 'Maldives',
        slug: 'maldives',
        country: 'Maldives',
        images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600&h=400&fit=crop'],
        shortDescription: 'Overwater villas, crystal clear waters, and pure luxury.',
        fullDescription: 'The Maldives is a tropical nation in the Indian Ocean composed of 26 ring-shaped atolls.',
        priceRange: { min: 2000, max: 5000 },
        category: 'beach',
        rating: 4.9,
        bestTimeToVisit: 'November to April',
        tags: ['beach', 'luxury', 'romantic', 'island'],
        createdAt: new Date(), updatedAt: new Date(),
    },
    {
        name: 'New York, USA',
        slug: 'new-york-usa',
        country: 'USA',
        images: ['https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&h=400&fit=crop'],
        shortDescription: 'The city that never sleeps — endless energy and diversity.',
        fullDescription: 'New York City is the most populous city in the United States, a global metropolis known for its iconic skyline, diverse culture, and world-class entertainment.',
        priceRange: { min: 1200, max: 4000 },
        category: 'city',
        rating: 4.6,
        bestTimeToVisit: 'April to June, September to November',
        tags: ['city', 'culture', 'food', 'shopping'],
        createdAt: new Date(), updatedAt: new Date(),
    },
];

(async () => {
    await connectDB();
    await ensureIndexes();
    const db = getDb();
    await db.collection('destinations').deleteMany({});
    await db.collection('destinations').insertMany(destinations);
    console.log(`✅ Seeded ${destinations.length} destinations.`);
    process.exit(0);
})();